sudo: required
install: true
language: java

services:
  - docker

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk version
  - mkdir -p "$HOME/.sdkman/etc"
  - echo "sdkman_auto_answer=true" > "$HOME/.sdkman/etc/config"
  - echo "sdkman_auto_selfupdate=true" >> "$HOME/.sdkman/etc/config"
  - sdk install java 8.0.202.hs-adpt

script:
  - sdk use java 8.0.202.hs-adpt
  - java -version
  - ./gradlew ci

after_failure:
  - "cat ./build/etcd4j-test.log"
  - "cat ./build/reports/dockerTest/index.html"
