sudo: false
language:
- java
before_install:
- ./src/main/bash/etcd_install.sh -p ./etcd-dist
script:
- ./src/main/bash/etcd_run.sh ./etcd-dist
- ./gradlew build
jdk:
- oraclejdk7
env:
  global:
    - CI_DEPLOY_USERNAME=fake
    - CI_DEPLOY_PASSWORD=fake
    - CI_TRAVIS=true